<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5c125d8781f32',
    'title' => __('E-Service Form Input', 'my-pages'),
    'fields' => array(
        0 => array(
            'key' => 'field_5c125efc8254f',
            'label' => __('Desciption', 'my-pages'),
            'name' => 'service_description',
            'type' => 'textarea',
            'instructions' => __('A short description about the service. What\'s it about? Whats the end-user goal?', 'my-pages'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 500,
            'rows' => 8,
            'new_lines' => '',
        ),
        1 => array(
            'key' => 'field_5c125f8744984',
            'label' => __('Field configuration', 'my-pages'),
            'name' => 'service_field_config',
            'type' => 'flexible_content',
            'instructions' => __('Add your fields below...', 'my-pages'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                '5c125f906fab9' => array(
                    'key' => '5c125f906fab9',
                    'name' => 'text_input',
                    'label' => __('Text input', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c135cfcdcfeb',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5c13774d0290c',
                            'label' => 'Unique field key',
                            'name' => 'key',
                            'type' => 'text',
                            'instructions' => 'This key must be unique for this form, and may not be changed later.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5c135dc4dcfec',
                            'label' => 'Instructions',
                            'name' => 'instructions',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        3 => array(
                            'key' => 'field_5c1267ede4365',
                            'label' => 'Conversional: Statement',
                            'name' => 'statement',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_5c135c3173d25',
                            'label' => 'Required?',
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Check this box if the user is required to fill this field',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        5 => array(
                            'key' => 'field_5c1387107b10c',
                            'label' => 'Enable validation',
                            'name' => 'validation',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Enable validation on this input',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        6 => array(
                            'key' => 'field_5c1387367b10d',
                            'label' => 'Validate as',
                            'name' => 'validation_requirement',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5c1387107b10c',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'email' => 'Email',
                                'phone' => 'Phone numer',
                                'didigts' => 'Digits',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5c135fccbdc96' => array(
                    'key' => 'layout_5c135fccbdc96',
                    'name' => 'text_area',
                    'label' => __('Textarea', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c135fccbdc97',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5c13772c0290b',
                            'label' => 'Unique field key',
                            'name' => 'key',
                            'type' => 'text',
                            'instructions' => 'This key must be unique for this form, and may not be changed later.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5c135fccbdc98',
                            'label' => 'Instructions',
                            'name' => 'instructions',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        3 => array(
                            'key' => 'field_5c135fccbdc99',
                            'label' => 'Conversional: Statement',
                            'name' => 'statement',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_5c135fccbdc9a',
                            'label' => 'Required?',
                            'name' => 'required',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Check this box if the user is required to fill this field',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5c137463a2fd3' => array(
                    'key' => 'layout_5c137463a2fd3',
                    'name' => 'single_choice',
                    'label' => __('Radio buttons', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c137463a2fd4',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5c1376dd0290a',
                            'label' => 'Unique field key',
                            'name' => 'key',
                            'type' => 'text',
                            'instructions' => 'This key must be unique for this form, and may not be changed later.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5c137463a2fd5',
                            'label' => 'Instructions',
                            'name' => 'instructions',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        3 => array(
                            'key' => 'field_5c137463a2fd6',
                            'label' => 'Conversional: Statement',
                            'name' => 'statement',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_5c137474a2fd8',
                            'label' => 'Options',
                            'name' => 'options',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => 'field_5c1374c9a2fd9',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add option',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5c1374c9a2fd9',
                                    'label' => 'Label',
                                    'name' => 'label',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => 60,
                                ),
                                1 => array(
                                    'key' => 'field_5c1374eda2fda',
                                    'label' => 'Value',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5c13794eccb3f' => array(
                    'key' => 'layout_5c13794eccb3f',
                    'name' => 'multiple_choice',
                    'label' => __('Checkboxes', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c13794eccb40',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5c13794eccb41',
                            'label' => 'Unique field key',
                            'name' => 'key',
                            'type' => 'text',
                            'instructions' => 'This key must be unique for this form, and may not be changed later.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5c13794eccb42',
                            'label' => 'Instructions',
                            'name' => 'instructions',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        3 => array(
                            'key' => 'field_5c13794eccb43',
                            'label' => 'Conversional: Statement',
                            'name' => 'statement',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_5c13794eccb44',
                            'label' => 'Options',
                            'name' => 'options',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => 'field_5c1374c9a2fd9',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add option',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5c13794eccb45',
                                    'label' => 'Label',
                                    'name' => 'label',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '40',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => 60,
                                ),
                                1 => array(
                                    'key' => 'field_5c13794eccb46',
                                    'label' => 'Value',
                                    'name' => 'value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '40',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                2 => array(
                                    'key' => 'field_5c137971ccb47',
                                    'label' => 'Required',
                                    'name' => 'required',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '20',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5c1384161a7cc' => array(
                    'key' => 'layout_5c1384161a7cc',
                    'name' => 'output_description',
                    'label' => __('Description', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c13841c1a7cd',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5c13846a1a7ce',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 6,
                            'new_lines' => '',
                        ),
                        2 => array(
                            'key' => 'field_5c1384821a7cf',
                            'label' => 'Conversional: Information',
                            'name' => 'statement_information',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 4,
                            'new_lines' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5c1385c6c73f3' => array(
                    'key' => 'layout_5c1385c6c73f3',
                    'name' => 'output_break',
                    'label' => __('Page break', 'my-pages'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5c1385dfc73f7',
                            'label' => 'Next chapter text',
                            'name' => 'button_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'button_label' => __('Add Field', 'my-pages'),
            'min' => 1,
            'max' => 100,
        ),
        2 => array(
            'key' => 'field_5c13a708c50d3',
            'label' => __('Custom response', 'my-pages'),
            'name' => 'service_response',
            'type' => 'group',
            'instructions' => __('Define a custom response to let the user what\'s happens next. What actions to take, or estimated waiting time.', 'my-pages'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5c13a802b2c0f',
                    'label' => __('Enable custom service response', 'my-pages'),
                    'name' => 'enabled',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => __('Yes, enable a custom response message.', 'my-pages'),
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                1 => array(
                    'key' => 'field_5c13a756c50d5',
                    'label' => __('Custom response heading', 'my-pages'),
                    'name' => 'heading',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_5c13a802b2c0f',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5c13a720c50d4',
                    'label' => __('Custom response content', 'my-pages'),
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => __('Text to show to the user when the form has been filled, keep this short.', 'my-pages'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_5c13a802b2c0f',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 6,
                    'new_lines' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-mypages',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}